apiVersion: platform.kubecon.io/v1alpha1
kind: CacheInstanceClaim
metadata:
  name: ${{ values.team }}-cache
  namespace: ${{ values.team }}
  labels:
    team: ${{ values.team }}
spec:
  size: ${{ values.size }}
  region: ${{ values.region }}
  team: ${{ values.team }}
  engine: redis
